image: gitpod/workspace-full-vnc
tasks:
  - init: pip3 install -r pygame
    command: python3 battleships.py
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python